#!/bin/bash

name=syncthing
BIN=/usr/bin/syncthing
USER=syncthing
LOG=/var/log/syncthing.log
CFG=/etc/syncthing
PORT=8384
PIDFILE=/var/syncthing.pid

CMD="${BIN} -home=${CFG} -gui-address=0.0.0.0:${PORT}"

start(){
    pid=`ps -ef | grep -v grep | grep -i "${CMD}" | awk '{print $2}'`
    if [[ -z $pid ]]; then
        mkdir -p ${CFG}
        chown -R $USER:$USER ${CFG}
        runuser -l $USER -c "${CMD}" >>${LOG} 2>&1 &
        pid=$!
        echo $pid > ${PIDFILE}
        RETVAL=$?
        if [ "$RETVAL" = "0" ]; then
            echo "$name start success"
        else
            echo "$name start failed"
        fi
    else
        echo "$name is running with PID:"
        echo "$pid"
        RETVAL=0
    fi
}

stop(){
    pid=`ps -ef | grep -v grep | grep -i "${CMD}" | awk '{print $2}'`
    if [[ ! -z $pid ]]; then
        kill -TERM $pid
        RETVAL=$?
        if [ "$RETVAL" = "0" ]; then
            echo "$name stop success"
        else
            echo "$name stop failed"
        fi
    else
        echo "$name is not running"
        RETVAL=1
    fi
}

status(){
    pid=`ps -ef | grep -v grep | grep -i "${CMD}" | awk '{print $2}'`
    if [[ -z $pid ]]; then
        echo "$name is not running"
        RETVAL=1
    else
        echo "$name is running with PID:"
        echo "$pid"
        RETVAL=0
    fi
}

case "$1" in
'start')
    start
    ;;
'stop')
    stop
    ;;
'status')
    status
    ;;
'restart')
    stop
    echo "wait 5s..."
    sleep 5
    start
    RETVAL=$?
    ;;
*)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac
exit $RETVAL